import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import Header from '@/components/Header';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <Header />
                <nav>
                    <Link href={'/'} style={{ fontSize: '48px' }}>
                        Home
                    </Link>
                    <span style={{ fontSize: '48px' }}>&nbsp;|&nbsp;</span>
                    {/* <Link href={'/login'} style={{ fontSize: '48px' }}>
                        Login
                    </Link> */}
                    {/* <span style={{ fontSize: '48px' }}>&nbsp;|&nbsp;</span> */}
                    <Link href={'/notice'} style={{ fontSize: '48px' }}>
                        Notice
                    </Link>
                </nav>
                {children}
            </body>
        </html>
    );
}
